### PR TITLE
eu-legal additions

### PR DESCRIPTION
**Pull request by jBangiev**

### CODE REVIEW

**Comment by studiokiwik** [comment]
whait is @hiddenSubmit in ogone_eu.tpl ?

**Comment by Quetzacoalt91** [comment]
Hi @jBangiev,

I know there is this this extra call like ```$this->display(FILE, 'ogone.tpl');```, but I guess that if take care to not return or show it, we won't have collision with eu-legal.

**Comment by jBangiev** [comment]
i've changed it

**Comment by Quetzacoalt91** [comment]
Hi @jBangiev and @alexsimple,

This PR has just been merged, thanks for your contribution.

Best regards

**Pull request merged**
